controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_fast_login:
    path: /fast-login/index
    controller: App\Controller\Auth\SecurityController::login
    methods: [GET, POST]
app_login:
    path: /login/index
    controller: App\Controller\Auth\SecurityController::login
    methods: [GET, POST]
app_logout:
    path: /logout/index
